apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: m347-grafana
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-service.m347-prometheus.svc.cluster.local:80
        access: proxy
        isDefault: true