apiVersion: v1
kind: Service
metadata:
  name: redmine-service
  namespace: m347-redmine
spec:
  type: NodePort
  selector:
    app: redmine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
