apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: m347-wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: bitnami/wordpress:latest
        ports:
        - containerPort: 8080
        env:
        - name: WORDPRESS_DATABASE_HOST
          value: mariadb-service
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: secret
              key: username
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: database_name
        - name: WORDPRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: WORDPRESS_USERNAME
        - name: WORDPRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: WORDPRESS_PASSWORD
        volumeMounts:
        - mountPath: /bitnami/wordpress
          name: wordpress-persistent-storage
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
