apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: m347-prometheus
spec:
  accessModes:
    - ReadWriteOnce                 #So kann nur ein Node gleichzeitig schreiben
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
