apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: m347-prometheus
spec:
  type: ClusterIP
  ports:
    - port: 80                        # Ingress ruft Port 80 auf
      targetPort: 9090                # Container hört auf 9090
  selector:
    app: prometheus