apiVersion: v1                    # Verwendete API-Version für PVC
kind: PersistentVolumeClaim       # Objekttyp: Persistenz (fordert Speicherplatz beim Cluster an)
metadata:                 
  name: mediawiki-db-pvc          # Interner Name des PVC, über den er im Deployment referenziert wird
  namespace: m347-mediawiki       # Namespace, in dem der PVC gespeichert ist
spec:
  accessModes:
    - ReadWriteOnce               # Nur ein Node darf gleichzeitig schreiben
  resources:
    requests:
      storage: 1Gi                # Speichergrösse (hier: 1 Gibibyte)
