apiVersion: apps/v1                              # API-Version für Deployments
kind: Deployment                                 # Objekttyp: Deployment
metadata:
  name: mediawiki                                # Name des Deployments
  namespace: m347-mediawiki                      # Namespace, in dem das Deployment ausgeführt wird
  labels:
    app: mediawiki                               # Label zur Gruppierung und Service-Verknüpfung
spec:
  replicas: 1                                    # Anzahl der gewünschten Pods (Replikate)
  selector:
    matchLabels:
      app: mediawiki                             # Verknüpft Selector mit Template-Label
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - name: mediawiki                        # Containername
          image: mediawiki:1.43                  # Docker-Image (offizielles MediaWiki-Image)
          ports:
            - containerPort: 8080                # Standardport für MediaWiki
          env:                                   # Umgebungsvariablen für Konfiguration
            - name: MEDIAWIKI_SITE_NAME
              valueFrom:
                configMapKeyRef:
                  name: mediawiki-config
                  key: MEDIAWIKI_SITE_NAME
            - name: MEDIAWIKI_SITE_LANG
              valueFrom:
                configMapKeyRef:
                  name: mediawiki-config
                  key: MEDIAWIKI_SITE_LANG
            - name: MEDIAWIKI_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mediawiki-config
                  key: MEDIAWIKI_DB_NAME
            - name: MEDIAWIKI_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mediawiki-config
                  key: MEDIAWIKI_DB_USER
            - name: MEDIAWIKI_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mediawiki-config
                  key: MEDIAWIKI_DB_HOST
            - name: MEDIAWIKI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediawiki-secret
                  key: MEDIAWIKI_DB_PASSWORD
          volumeMounts:
            - name: mediawiki-storage
              mountPath: /bitnami/mediawiki     # Mount-Pfad für persistente Daten
      volumes:
        - name: mediawiki-storage
          persistentVolumeClaim:
            claimName: mediawiki-pvc            # Bindung an PVC

