apiVersion: v1                              # Verwendete API-Version für Secret
kind: Secret                                # Objekttyp: Secret (Zugangsdaten / Token)
metadata:
  name: mediawiki-secret                    # Interner Name der Secret, über den sie im Deployment referenziert wird
  namespace: m347-mediawiki                 # Namespace, in dem die Secret gespeichert ist
type: Opaque                                # Standardtyp für benutzerdefinierte Schlüssel-Wert-Paare
stringData:                                 # Ab hier: Schlüssel-Wert-Paare
  MARIADB_ROOT_PASSWORD: supergeheim        # Diese können in Klartext angegeben werden (werden intern automatisch Base64-kodiert)
  MEDIAWIKI_DB_PASSWORD: mwpass123
